config/routes.rb
Depot::Application.routes.draw do
  get 'admin', to: 'admin#index'
  controller :sessions do
    get 'login', action: :new
    post 'login', action: :create
    delete 'logout', action: :destroy
  end

  resources :users

  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end

  

  

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Pragprog Book Online Store
    == stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track" => true
    == javascript_include_tag "application", "data-turbolinks-track" => true
    == csrf_meta_tags
  body class="#{controller.controller_name}"
    #banner
      == form_tag store_path, class: 'locale' do
        = select_tag 'set_locale',
          options_for_select(LANGUAGES, I18n.locale.to_s),
          onchange: 'this.form.submit()'
        = submit_tag 'submit'
        = javascript_tag "$('.locale input').hide()"
      == image_tag("logo.png")
      == @page_title || t('.title')

    #columns
      #side
        - if @cart
          = hidden_div_if(@cart.line_items.empty?, id: 'cart') do
            = render @cart
        #date
          == Time.new.ctime
        ul
          li: a[href="http://www...."] = t('.home')
          li: a[href="http://www..../faq"] = t('.questions')
          li: a[href="http://www..../news"] = t('.news')
          li: a[href="http://www..../contact"] = t('.contact')
        - if session[:user_id]
          ul
            li = link_to 'Orders', orders_path
            li = link_to 'Products', products_path
            li = link_to 'Users', users_path
          = button_to 'Logout', logout_path, method: :delete
      #main
        == yield